//! # ServiceConfig — TOML-based configuration for the nmd-service systemd daemon
//!
//! Loads runtime parameters from a `config.toml` file (or falls back to built-in defaults).
//! On startup, also reads the HMAC pre-shared key from `/etc/nmd/secret.key`.
//!
//! ## Configuration File Format (`config.toml`)
//!
//! ```toml
//! # Desktop applet destination address
//! host = "192.168.1.10"
//! port = 51057
//!
//! # How often to collect + send metrics (seconds)
//! refresh_interval_secs = 1
//!
//! # Unique machine identifier — auto-detected from hostname if not set
//! machine_id = "pluto"
//! ```
//!
//! ## Secret Key Management (Worf Phase 1A)
//!
//! The HMAC pre-shared key is stored at `/etc/nmd/secret.key` with `0600` permissions.
//! It must be exactly 32 bytes for HMAC-SHA256. This file is generated by the install script
//! (`install-scripts/install.sh`) on each remote machine and shared out-of-band to the desktop applet.

use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

/// Default UDP destination: desktop applet listening address.
const DEFAULT_HOST: &str = "127.0.0.1";
const DEFAULT_PORT: u16 = 51057;
/// Default collection/send interval in seconds (every 1 second for accurate CPU delta measurement).
const DEFAULT_REFRESH_INTERVAL_SECS: u64 = 1;

/// Default configuration file path for nmd-service (loaded when no --config is given).
pub const DEFAULT_CONFIG_PATH: &str = "/etc/nmd/config.toml";

/// Path to the HMAC pre-shared key file on remote machines.
pub const SECRET_KEY_PATH: &str = "/etc/nmd/secret.key";
/// Required length of the secret key in bytes (HMAC-SHA256 uses 32-byte keys).
const SECRET_KEY_LEN: usize = 32;

/// Runtime configuration for `nmd-service`, loaded from TOML at startup.
#[derive(Debug, Clone, Deserialize)]
pub struct ServiceConfig {
    /// Desktop applet IP address to send UDP packets to (default: "127.0.0.1").
    #[serde(default = "default_host")]
    pub host: String,
    /// UDP port on the desktop applet (default: 51057).
    #[serde(default = "default_port")]
    pub port: u16,
    /// Collection + transmission interval in seconds (default: 1 = every 1s for accurate CPU delta measurement).
    #[serde(default = "default_refresh_interval_secs")]
    pub refresh_interval_secs: u64,
    /// Unique machine identifier — used for auto-registration and HMAC replay protection.
    /// Falls back to the system hostname if not set in config or empty string.
    #[serde(default = "default_machine_id")]
    pub machine_id: String,
    /// Filesystem path to the HMAC pre-shared key file (default: `/etc/nmd/secret.key`).
    #[serde(default = "default_secret_path")]
    pub hmac_secret_path: String,
}

/// Serde default functions for partial TOML config support.
fn default_host() -> String { DEFAULT_HOST.to_string() }
fn default_port() -> u16 { DEFAULT_PORT }
fn default_refresh_interval_secs() -> u64 { DEFAULT_REFRESH_INTERVAL_SECS }
fn default_machine_id() -> String { "unknown".to_string() }
fn default_secret_path() -> String { SECRET_KEY_PATH.to_string() }

impl Default for ServiceConfig {
    fn default() -> Self {
        // Auto-detect hostname as machine_id if not explicitly configured.
        let machine_id = hostname::get()
            .map(|h| h.to_string_lossy().into_owned())
            .unwrap_or_else(|_| "unknown".to_string());

        ServiceConfig {
            host: DEFAULT_HOST.to_string(),
            port: DEFAULT_PORT,
            refresh_interval_secs: DEFAULT_REFRESH_INTERVAL_SECS,
            machine_id,
            hmac_secret_path: SECRET_KEY_PATH.to_string(),
        }
    }
}

impl ServiceConfig {
    /// Load configuration from a TOML file at the given path.
    ///
    /// Falls back to [`ServiceConfig::default()`] if the file doesn't exist or is malformed,
    /// merging any provided fields over defaults so partial configs are valid. Fields not present
    /// in the TOML use `#[serde(default)]` semantics — `machine_id` and `hmac_secret_path` fall
    /// back to auto-detected hostname and `/etc/nmd/secret.key` respectively.
    pub fn load(config_path: &str) -> Self {
        let mut config = ServiceConfig::default();

        match fs::read_to_string(config_path) {
            Ok(contents) => {
                // Parse TOML into a partial ServiceConfig, then merge over defaults.
                // Fields not in the TOML retain their default values via serde's #[serde(default)].
                match toml::from_str::<ServiceConfig>(&contents) {
                    Ok(parsed) => {
                        config.host = parsed.host;
                        config.port = parsed.port;
                        config.refresh_interval_secs = parsed.refresh_interval_secs;
                        // Only override machine_id if the TOML actually specified one (non-empty).
                        if !parsed.machine_id.is_empty() && parsed.machine_id != "unknown" {
                            config.machine_id = parsed.machine_id;
                        }
                        config.hmac_secret_path = parsed.hmac_secret_path;
                        log::info!("Loaded config from {} — host={}, port={}, refresh_interval={}s",
                                   config_path, config.host, config.port, config.refresh_interval_secs);
                    }
                    Err(e) => {
                        log::warn!(
                            "Failed to parse config at {}: {} — using defaults (machine_id={})",
                            config_path, e, config.machine_id
                        );
                    }
                }
            }
            Err(_) => {
                log::info!(
                    "No config file at {}; using defaults (machine_id={})",
                    config_path,
                    config.machine_id
                );
            }
        }

        config
    }

    /// Resolve the destination `SocketAddr` for UDP packets.
    pub fn dest_addr(&self) -> std::net::SocketAddr {
        format!("{}:{}", self.host, self.port)
            .parse()
            .expect("Invalid host/port in ServiceConfig")
    }

    /// Load the HMAC pre-shared key from `hmac_secret_path`.
    ///
    /// Returns a 32-byte key for HMAC-SHA256. Fails if the file is missing, unreadable,
    /// or not exactly `SECRET_KEY_LEN` bytes (per Worf's security requirements).
    pub fn load_secret_key(&self) -> Result<Vec<u8>, std::io::Error> {
        use std::os::unix::fs::PermissionsExt;

        let path = PathBuf::from(&self.hmac_secret_path);

        // Read the entire file contents.
        let data = fs::read(&path)?;

        // Validate file permissions are 0600 (owner read/write only) per Worf's security requirements.
        let metadata = std::fs::metadata(&path)?;
        let perms = metadata.permissions();
        let mode = perms.mode() & 0o777;
        if mode != 0o600 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::PermissionDenied,
                format!("Secret key at {} has permissions {:o} — expected 0600", path.display(), mode),
            ));
        }

        // Validate that the key is exactly 32 bytes (HMAC-SHA256 requirement).
        if data.len() != SECRET_KEY_LEN {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!(
                    "Secret key at {} is {} bytes — expected exactly {}",
                    path.display(),
                    data.len(),
                    SECRET_KEY_LEN
                ),
            ));
        }

        log::info!("Loaded HMAC secret key from {} ({} bytes)", path.display(), data.len());
        Ok(data)
    }
}

/// Lightweight hostname detection without pulling in the `hostname` crate.
mod hostname {
    use std::process::Command;

    pub fn get() -> Result<std::ffi::OsString, std::io::Error> {
        let output = Command::new("hostname").output()?;
        if output.status.success() {
            Ok(std::str::from_utf8(&output.stdout)
                .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?
                .trim()
                .to_string()
                .into())
        } else {
            Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                "hostname command failed",
            ))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Default config has valid host/port/interval (Beverly writes after implementation).
    #[test]
    fn test_config_defaults() {
        let config = ServiceConfig::default();
        assert!(!config.host.is_empty());
        assert!(config.port > 0);
        assert!(config.refresh_interval_secs >= 1); // Minimum sane interval
        assert!(!config.machine_id.is_empty());
    }

    /// dest_addr parses correctly from host + port (Beverly writes after implementation).
    #[test]
    fn test_dest_addr_parses() {
        let config = ServiceConfig::default();
        let addr = config.dest_addr();
        assert_eq!(addr.port(), DEFAULT_PORT);
    }

    /// Loading non-existent config file falls back to defaults (Beverly writes after implementation).
    #[test]
    fn test_load_nonexistent_config() {
        let config = ServiceConfig::load("/nonexistent/path/config.toml");
        assert_eq!(config.port, DEFAULT_PORT);
        assert_eq!(config.refresh_interval_secs, DEFAULT_REFRESH_INTERVAL_SECS);
    }
}