# Receiver config for test
udp_port = 51057

[[machines]]
name = "a"
host = "127.0.0.1"
port = 51057
enabled = true

[[machines]]
name = "b"
host = "127.0.0.1"
port = 51057
enabled = true

[[machines]]
name = "c"
host = "127.0.0.1"
port = 51057
enabled = true

[[machines]]
name = "d"
host = "127.0.0.1"
port = 51057
enabled = true

[[machines]]
name = "e"
host = "127.0.0.1"
port = 51057
enabled = true
